#!/bin/bash

set -eu
set -o pipefail

# File name of post to publish must be provided as argument
if [[ -z "${1}" ]] ; then
    echo "Blog post file name not specified" >&2
    exit 1
fi
typeset -r FILENAME="${1}"
echo "Publishing ${FILENAME}"

# Change to the directory containing this script
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]] ; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
cd -P "$(dirname "$SOURCE")"

# Check we are on branch "source"
BRANCH_NAME="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH_NAME=""
BRANCH_NAME="${BRANCH_NAME##refs/heads/}"
if [[ "${BRANCH_NAME}" != "source" ]] ; then
    echo "Not on source branch"
    exit 2
fi

# Update dates and status in post metadata
typeset -r MODIFICATION_DATE=$(date +"%Y-%m-%d %H:%M")

if grep '^Status: draft$' "${FILENAME}" ; then
    sed -i '.backup'                              \
        -e "s/^Date:\ .*$/Date:\ ${MODIFICATION_DATE}"/ \
        -e 's/^Status: draft$/Status: published/' \
    ${FILENAME}
fi

sed -i '.backup'                                    \
    -e "s/^Modified: .*$/Modified: ${MODIFICATION_DATE}/" \
${FILENAME}

# Commit and push changes on source branch to GitHub
git add ${FILENAME}
git commit -m"Published ${FILENAME}"
git push

# Rebuild site locally and publish
make -C .. html
make -C .. github

# Get post title for tweet (xargs trims the leading whitespace)
POST_TITLE=$(grep "^Title: .*$" "${FILENAME}" | cut -d ":" -f2 | xargs)
if [[ -z "${POST_TITLE}" ]] ; then
    echo "Error determining title of post"
    exit 3
fi

# Construct the tweet to accompany the publication
TWEET_BASE="New blog post published: \\\"${POST_TITLE}\\\" "
typeset -ir TWEET_MAXLEN=110 # Allow 30 characters for bit.ly shortened link
# Maximum length of title if it needs to be shortened
typeset -i TWEET_TITLE_MAXLEN=$(expr ${TWEET_MAXLEN} \- 21)
typeset -i TWEET_LEN=${#TWEET_BASE}
if [[ "${TWEET_LEN}" -gt "${TWEET_MAXLEN}" ]] ; then
    TWEET_BASE="New blog post: \\\"${POST_TITLE}\\\" "
fi
TWEET_LEN=${#TWEET_BASE}
if [[ "${TWEET_LEN}" -gt "${TWEET_MAXLEN}" ]] ; then
    TWEET_BASE="New blog post: \\\"${POST_TITLE}\\\" "
fi
if [[ "${TWEET_LEN}" -gt "${TWEET_MAXLEN}" ]] ; then
    POST_TITLE="$(echo ${POST_TITLE} | cut -c1-${TWEET_TITLE_MAXLEN})"
    TWEET_BASE="New blog post: \\\"${POST_TITLE}...\\\" "
fi

# Get URL of the post
typeset -r BASE_URL="http://0x7df.github.io"
POST_URL=$(grep '^Slug: .\+$' ${FILENAME} | cut -d":" -f2 | xargs)
if [[ -z "${POST_URL}" ]] ; then
    POST_URL=$(basename -s .md ${FILENAME}) 
fi
if [[ -z "${POST_URL}" ]] ; then
    echo "Error determining URL of post"
    exit 4
fi

# Add trigger for IFTTT Maker channel here, using curl, to Tweet link to new
# post
TWEET_BODY="${TWEET_BASE}${BASE_URL}/${POST_URL}.html"
PAYLOAD="{\"value1\":\"${TWEET_BODY}\", \"value2\":\"test2\", \"value3\":\"test3\"}"
APIKEY=$(cat ./file_containing_secret_key)
#curl -X POST -H "Content-Type: application/json" \
#    -d "${PAYLOAD}" \
#    "https://maker.ifttt.com/trigger/0x7df_blog_post_published/with/key/${APIKEY}"

