#!/usr/bin/env bash

set -eu
set -o pipefail

if [[ $# != 1 ]] ; then
    echo "Provide article title as argument" >&2
    exit 1
fi

SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]] ; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
cd -P "$(dirname "$SOURCE")"

TITLE=$(echo ${1} | tr " " "-" | tr [[:upper:]] [[:lower:]])
DATE=$(date "+%Y-%m-%d %H:%M")

echo "Title: ${1}
Date: ${DATE}
Category: ${2} 
Modified: ${DATE}
Tags: 
Slug: 
Author: 0x7df
Summary: 
Status: draft

" > ${TITLE}.md

mvim ${TITLE}.md

