#!/usr/bin/env bash

set -eu
set -o pipefail

SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]] ; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
cd -P "$(dirname "$SOURCE")"

typeset -r POST_TITLE="$1"
typeset -r POST_BASE=$(basename -s .md "$POST_TITLE")
echo $POST_TITLE
echo $POST_BASE

make -C .. html
PORT=8000 make -C .. serve &

open http://localhost:8000/drafts/${POST_BASE}.html

