#!/usr/bin/env bash

set -eu
set -o pipefail

SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]] ; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
cd -P "$(dirname "$SOURCE")"

POST_TITLE="$1"
echo $POST_TITLE

POST_BASE=$(basename -s .md "$POST_TITLE")
echo $POST_BASE

make -C .. html
make -C .. serve &
open http://localhost:8000/drafts/${POST_BASE}.html

