name: build

on:
    workflow_dispatch:
    pull_request:
        branches:
            - source
        types:
            - closed

jobs:
    download:
        runs-on: ubuntu-latest

        steps:

            - name: Check out repo
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pelican[markdown]
                  pip install pelican-render-math
                  pip install ghp-import

            - name: Run download script
              run: |
                  git checkout source
                  git clone https://github.com/0x7df/nest.git
                  pelican-themes -v --install nest
                  make html
                  make github

